workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      cache:
        paths:
          - .pub-cache
          - ios/Pods
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Install iOS pods
        script: pod install --repo-update
      - name: Build iOS IPA (unsigned)
        script: flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
