workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUILD_MODE: release
        IOS_EXPORT_METHOD: ad-hoc
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Prepare iOS
        script: |
          cd ios
          pod install
      - name: Build IPA
        script: |
          flutter build ipa --release --export-options-plist export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa

  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      android: default
      vars:
        BUILD_MODE: release
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
