workflows:
  ios-workflow:
    name: iOS Build Workflow (Unsigned)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        FLUTTER_BUILD_MODE: release
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install --repo-update
          cd ..
      - name: Build unsigned iOS IPA
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/**/*.ipa
