workflows:
  flutter-workflow:
    name: Flutter CI/CD
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      cache:
        flutter: true
        cocoapods: true
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: iOS build
        script: |
          cd ios
          pod install --repo-update
          cd ..
          flutter build ipa --release --no-codesign
      - name: Android build
        script: |
          flutter build apk --release
    artifacts:
      - build/ios/ipa/*.ipa
      - build/app/outputs/flutter-apk/app-release.apk
