name: wynford_weather_mission
description: A secure weather alert app with SMS login, admin/public roles, and real-time warnings.

publish_to: 'none' # Not publishing to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.24.0
  firebase_auth: ^5.12.0
  cloud_firestore: ^4.8.5
  flutter_local_notifications: ^13.0.0
  provider: ^6.1.5
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/alert.mp3
