name: wynford_weather_mission
description: A secure weather alert app with SMS login, admin/public roles, and real-time warnings.

publish_to: 'none' # Not publishing to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.5.0
  firebase_auth: ^0.0.1
  cloud_firestore: ^0.0.3
  flutter_local_notifications: ^1.5.0
  provider: ^2.0.0
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/alert.mp3
